### ISSUE TITLE
doc: how to use golang.org/net/trace for client-side quorum call tracing

### ISSUE THREAD

**Issue by meling** [relab/gorums#10]
We need to document how to use tracing.

- What are the command lines to use?
- What it helps us to debug?
- Could w provide an example of how to trace something?

**Comment by meling** [comment]
Pinging this one. It would be great to have an example to make it easy to test what it does. (I didn't make an effort to figure it out though... I'm lazy).

**Comment by tormoder** [comment]
Yes, I can try to make a small example.

I have been a little hesitant about touching the tracing stuff since:
* I'm not sure how useful it is right now.
* There has been talk about tracing standardization for Go, but I can't see that it has lead to anything concrete. See e.g. https://groups.google.com/forum/#!topic/go-kit/AHgWcvCBat0.
And https://github.com/google/gotrace is empty.

**Comment by meling** [comment]
The go-kit thread you referenced hints at http://opentracing.io being relevant. I've not looked at it. I did notice that gRPC is still using `golang.org/x/net/trace`. I'm also not sure how useful it is. Personally, I tend to log to files and examine the logs, rather than trying to look at things in a browser, but there may be things here that I don't see, hence the need for documenting it (or pointing to a good reference which I and others can look at to find out more). I know that @s111 used prometheus for `rkv`.

**Comment by meling** [comment]
Closing this as it is outdated. We have also removed tracing from the code. If we need it, we will add it again later.
