### ISSUE TITLE
An error occurred while using the call type quorum call (Original: 使用调用类型——仲裁调用，报错)

### ISSUE THREAD

**Issue by 614709853** [relab/gorums#191]
1. Define the hotstuff.proto file：
```
service Hotstuff {
	rpc VidFetch(View) returns (ReceiveChunk) {
		option (gorums.quorumcall) = true;
	}
}
message View {
  uint64 view = 1;
}
// The Chunk and Proof structs are already defined
message ReceiveChunk {
  bytes root_hash = 1;
  Chunk chunk = 2;
  Proof proof = 3;
}
```
2. Compile the proto file to generate hotstuff_gorums.pb.go and hotstuff.pb.go
3. Running encounters an error:：
```
2024/12/11 11:18:47 failed to run experiment: failed to start replicas: rpc error: code = Unknown desc = failed to create configuration: unknown option type: {}
```
4. This should be a relatively classic error, but I'm not very familiar with this library. Could you please explain it?

**Comment by meling** [comment]
I don't see anything wrong with your protobuf definition. The error message is unrelated to the `option (gorums.quorumcall)`.

Could you share how you are calling the:
```go
NewConfiguration(opts ...gorums.ConfigOption)
```
function; what arguments are you passing? It is defined in your `hotstuff_gorums.pb.go`, so you can use that to search backwards to find invocations.

Here is an example of how it should be called: [examples/storage/client.go#L27](https://github.com/relab/gorums/blob/master/examples/storage/client.go#L27).

That is, this error can happen if you pass the `NewConfiguration` function an option that does not match one of the required input types: `NodeListOption` or `QuorumSpec` (the `ConfigOption` is an empty interface that provides flexibility, but makes it hard to give adequate error messages.) I don't recall exactly why this isn't using generics to prevent this possibility; I will look into it.

However, since it appears you are using the hotstuff experiment framework, it seems more likely that you have forgotten to pass an argument or that your config file has a mistake. Perhaps we need to add some improved checks in that framework to avoid this type of issue with bad error messages.

**Comment by 614709853** [comment]
Thank you for your reply. I need to conduct some experiments based on this library (https://github.com/relab/hotstuff). Currently, I haven't made too many modifications to the code in this library. The hotstuff.proto file in the hotstuff-master/internal/proto/hotstuffpb directory of this library defines a Fetch function, and I followed its pattern to add the aforementioned VidFetch function, but then the aforementioned exception occurred.

**Comment by meling** [comment]
Two questions:
1. How did you execute the binary? (via the Makefile, or some other approach?)
2. What does your configuration file look like? (running locally or on a cluster via ssh?)

It is difficult to help debug without these details.

**Comment by meling** [comment]
Closing as this does not appear to be a gorums problem.
