### ISSUE TITLE
Change node ids from integer to string -> string pairs

### ISSUE THREAD

**Issue by s111** [relab/gorums#29]
I found the whole Raft ID to Gorums ID and back translation to be really tedious, what do you think of this change?

- Change node ids from an `uint32` to a `string -> string` pair.
  - This removes the need for an application id to gorums id table, making the developer responsible for the id-scheme used, I find this preferable.
  - While this is solved by using hostnames and DNS, it also avoids the problem of node A having IP X seen from B while IP Y seen from C.

**Comment by meling** [comment]
I'm considering whether or not we should implement this. @s111 could you please provide some sample code for how you would use this in Raft? I've looked at `membership.go` and `raft.go`, and it looks to be the places where this would be applicable, but it is not obvious to me without spending a lot of time analyzing this.

**Comment by meling** [comment]
I've looked more into the use of Raft IDs. Seems like Raft uses `uint64` instead of `uint32` and thus needs to remap these IDs all over the place, which seems unnecessary. I don't understand why `uint64` is used? There will never be a Raft cluster with more than _max_(`uint32`) nodes. I'm pretty sure that we can solve the uniqueness problem with a hash over the hostname/port string and ordering the IDs in the range [0,_n_-1]. What am I missing @s111  @tormoder?  And why would using a `string -> string` pair help? Would the key be the application-level ID and the value be the Gorums level ID? When do you need a different application-level ID for nodes/replicas?

I've been pondering (without looking at the details) whether maybe the `Configuration` and `Node` objects should be protobuf messages, so that these could be sent over the wire.

**Comment by s111** [comment]
I think the reason for `uint64` was so that I could have an interface that was compatible with `etcd/raft` and `hashicorp/raft`.

The problem, if I remember correctly, with Gorums is that the `id` is generated from the resolved TCP address of the server. Thus, you cannot remove a server from the cluster and add it back without changing the IP.

An example: You have a cluster of 3 servers. There is a problem with the server with id 2 and it needs to be taken offline and started from a fresh state. You can't do this without also changing the IP as Gorums will always assign it id 2, and the cluster assumes something about the state of the server with id 2. This causes inconsistencies. There is no way to say, give this server id 4.

Another (smaller) problem, is that a server's IP might be different seen from different servers.

I think a globally unique ID is a must, we shouldn't try to figure out what a server's ID is, the configuration should state it.

**Comment by meling** [comment]
Good points @s111 !! Thanks for helping to clarify these issues! I guess @tfrausin could take a look at this problem in the context of his thesis work on reconfiguration. @leandernikolaus 

I remember there were some interesting work from a few years back in the context of some next generation Internet projects (I think out of Princeton) that looked at things that are related to the problem of IDs and mapping to nodes vs service names and stuff... I will try to digg that up; maybe we can learn something from that!

**Comment by meling** [comment]
Here is the paper that was thinking about in this context; it is much broader than we need, but there could be some lessons to be taken from this work:
```
Serval: An End-Host Stack for Service-Centric Networking
Erik Nordstrom, David Shue, Prem Gopalan, Rob Kiefer, Matvey Arye, Steven Ko, Jennifer Rexford, and Michael J. Freedman
Proc. 9th Symposium on Networked Systems Design and Implementation (NSDI '12) San Jose, CA, April 2012.
```

**Comment by s111** [comment]
If you "reverse" my previous argument, you actually have a bigger problem: You cannot change a server's IP without also changing the Gorums ID. That is, if you use the Gorums ID directly in your Raft implementation, you would have to do a reconfiguration to get the server to join the cluster again with a new IP.

If I specify a server with the address `raft1.example.com`, I would expect Gorums to handle the underlying IP changing, and it looks like it does as it passes the string unchanged to gRPC. However, if I where to restart the server, the ID for `raft1.example.com` would change, as the restart causes the server ID to be recalculated using the new IP. Thus, a restart could change a server's configuration unintentionally.  

As I remember I fixed this problem by enforcing that Gorums returns node IDs in the same order that the server addresses were initially given. Thus, it's easy to create a lookup Raft ID <-> Gorums ID.

My suggestion, I think, was basically doing this:

Current:
```go
func NewManager(nodeAddrs []string, opts ...ManagerOption) (*Manager, error) { ... }
func (m *Manager) NewConfiguration(ids []uint32, qspec QuorumSpec) (*Configuration, error) { ... }
```

New:
```go
type NodeID string // Whatever is meaningful for the user of Gorums.
type Addr string // DNS resolvable string for grpc.Dial.

func NewManager(cluster map[NodeID]Addr, opts ...ManagerOption) (*Manager, error) { ... }
func (m *Manager) NewConfiguration(ids []NodeID, qspec QuorumSpec) (*Configuration, error) { ... }
```

I don't think Gorums needs to resolve `Addr` it can just be passed on to gRPC.
Also, I only added the `Addr` type for clarification, it's probably best to leave it as `string` as that's what grpc.Dial uses.

**Comment by tormoder** [comment]
I agree with @s111 about not resolving the address.

But maybe the `NodeID` type should be something other than a string? Or maybe it doesn't matter.

I don't how it was done for raft, but I think a common thing is you often want (in your application) to keep the ids of your current replica set of `n` nodes in the range `[0,n)` so you can index a slice instead of using maps (indexing the log/slots).

So you still must have a application level mapping from a "locked" set of ids, `[0,n)` that is mapped onto a set of `NodeID`s (representing a unique node) that can change after a reconfiguration, e.g. replica `n` can be `id-foo` and later `ìd-bar`.

How did you do this for raft?

**Comment by meling** [comment]
@tormoder Quick pointer to Raft code that takes care of translating between Raft ID (uint64) and NodeID (uint32):
https://github.com/relab/raft/blob/master/raftgorums/membership.go#L262

@s111 wrote:
> If I specify a server with the address raft1.example.com, I would expect Gorums to handle the underlying IP changing, and it looks like it does as it passes the string unchanged to gRPC. However, if I where to restart the server, the ID for raft1.example.com would change, as the restart causes the server ID to be recalculated using the new IP. Thus, a restart could change a server's configuration unintentionally.

So if I understand this correctly, the fact that the code here:
https://github.com/relab/gorums/blob/master/dev/mgr.go#L81
resolves the TCP endpoint (IP address and port) causes the node ids to be tied to the IP/port pair rather than a DNS name, even if a DNS name was used as input. 

It seems to me that one solution could be to calculate the NodeID hashes based on the input string (DNS name and port), rather than the IP/port string. Either way, it is easy to sort these NodeID hashes to obtain a `[0,n)` range, which I think is important. And since a configuration with `n` nodes is immutable there is no reason to recompute them in the context of a single configuration. Those DNS names will always be tied to a specific ID in the `[0,n)` range for that configuration. 

PS: We probably don't need to compute hashes if IDs are in a `[0,n)` range, since we could just order the nodes based on the strings, avoiding the hashes all together, or order them based on the input order.

One question I have is if exposing those `[0,n)` NodeIDs through the `Node` type leaves us open to problems down the road where people using node ids in one configuration thinking that the same node id is reusable in another configuration. They wouldn't be unique across configurations, whereas a hash-based ID would be unique (with high probability).

So, without concluding anything now, there is a case to be made for having an `Index()` for each node that is unique within a configuration, and a `NodeID()` that is unique across configurations. Will continue to think about this more. @tfrausin feel free to pitch in your thoughts as well.

**Comment by Raytar** [comment]
We could use the `ManagerOption` functions to allow users to specify node ids. It could, for example, work like this: 

```go
func NewManager(opts ...ManagerOption) (*Manager, error) { ... }

// specifying id and address for each node
var nodes map[NodeID][Addr]
mgr, err := NewManager(WithNodeMapping(nodes), ...)

// only specify node addresses, allowing Gorums to choose ids
var nodeAddrs []Addr
mgr, err := NewManager(WithNodeAddrs(nodeAddrs), ...)
```

This way, simple applications that don't need to specify node ids can let Gorums choose them in the same way that it works now.
