### ISSUE TITLE
Missing import when using bytes message field

### ISSUE THREAD

**Issue by meling** [relab/gorums#38]
The `rec.proto` file in [recstore](https://github.com/relab/recstore/blob/master/rec.proto) generates `pb.go` file without `bytes` import.

**Comment by meling** [comment]
Could you take a look at this @tormoder ?  It is quite confusing, and this whole import thing is poorly designed (not your fault!!)  It should (possibly) have been solved as I propose in [issue 434](https://github.com/golang/protobuf/issues/434).

**Comment by tormoder** [comment]
Actually, we're using:
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L1414
and not the official golang/protobuf repository.

I think the reason is that before c67d83bf5d6c6a2263c the gogo/protobuf Equal and VerboseEquals plugins imported the `bytes` package to do comparisons if any messages had byte fields in them. We therefore ignored this import if we had messages with `[]byte` fields.

I can remove this logic to make recstore code generation work properly, but this will again break byzq, since it uses the gogo/protobuf Equals pluigin for tests (https://github.com/relab/byzq/blob/master/byzq.proto#L6). It will create a double `bytes` import.

I also now see that we use the `bytes` package in the tracing code, so we should always import it, but the problem described above still remains.

The real fix would be to utilize this (again gogo/protobuf):
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/helper.go#L98

Example: https://github.com/gogo/protobuf/blob/master/plugin/equal/equal.go#L193

I think this is what you are asking for in your upstram protobuf issue, but I haven't had time to study it closely yet.

**Comment by meling** [comment]
Thanks @tormoder. This was helpful. I think it makes sense to use the gogo APIs. I was actually thinking about trying to avoid the extra dependency on gogo, but it is probably a better choice to use it since it should also generate faster marshalling code ( I think ? )

**Comment by meling** [comment]
@tormoder: Tried the helper stuff. Currently I'm doing this:
```go
	g.PluginImports = generator.NewPluginImports(g.Generator)
	sort.Strings(staticImports)
	for _, simport := range staticImports {
		if ignore := ignoreImport[simport]; ignore {
			continue
		}
		g.NewImport(simport).Use()
	}
	g.NewImport("golang.org/x/net/trace").Use()
	g.NewImport("google.golang.org/grpc/codes").Use()
	g.NewImport("google.golang.org/grpc/status").Use()
```
This results in:
```go
import encoding_binary "encoding/binary"
import hash_fnv "hash/fnv"
import io "io"
import log "log"
import net "net"
import sort "sort"
import strings "strings"
import sync "sync"
import time "time"
import golang_org_x_net_trace "golang.org/x/net/trace"
import google_golang_org_grpc_codes "google.golang.org/grpc/codes"
import google_golang_org_grpc_status "google.golang.org/grpc/status"

import (
        context "golang.org/x/net/context"
        grpc "google.golang.org/grpc"
)
```
You basically need to use the full underscore path, which you can get to by the Use() method, but since our codebase is pre-defined as templates, this makes it a bit difficult to use this approach. Any ideas??

**Comment by meling** [comment]
Just found an interesting project related to NATS that is also generating code based on templates; see [here](https://github.com/chop-dbhi/nats-rpc). The trick they do to avoid the issues with the import statements they do is to simply generate the output file separately from the `pb.go` file generated by `protoc`. Not sure that would work for us though, since we rely on a different options, that wouldn't be found by the standard `protoc` compiler. But it might be worth checking it out some, to see if we can learn some tricks from their generator.

**Comment by meling** [comment]
Closing after commit 4079a91
