### ISSUE TITLE
Allow creating multiple overlapping configurations

### ISSUE THREAD

**Issue by leandernikolaus** [relab/gorums#61]
#### Problem
Currently, [`NewConfiguration`](https://github.com/relab/gorums/blob/master/dev/mgr.go#L222) only creates a new configuration, if no previous configuration with the same ids exists. Otherwise, it returns a reference to an already existing configuration. This raises the following issues:
1. It is not possible to create multiple configurations with identical nodes.
2. When recreating a configuration, the returned configuration will actually not use the QSpec provided.
3. It is not possible to garbage collect configurations.

I believe it is desirable to allow multiple configurations with the same set of nodes. This allows concurrent Quorum Calls to use different QSpecs. This allows maintaining call specific data in the QSpec without concurrency control.
Updating state in the QSpec can, for example, be useful to store, which replies have been successfully validated.

#### Fix
I want to propose to remove the `configs` map. Every call to `NewConfiguration` should indeed return a new configuration. The application can maintain them by reference. When the application does no longer references the configuration it should be garbage collected.
An interesting question is whether configuration ids should also be removed. Configuration ids allow to easily identify within and across processes if two configurations use the same underlying set of nodes.

What do you think @tormoder @meling

**Comment by meling** [comment]
A few observations. 

1. `NewConfiguration` does not check whether or not `qspec` is `nil`, and so if someone actually does this, it will fail when trying to deliver a reply instead of immediately when creating the new configuration. PS: Several tests pass `nil` for `qspec`...
2. If we want to keep the map of configs, we could include the `qspec` as part of the `cid` by adding 

```go
	binary.Write(h, binary.LittleEndian, qspec)
```

(note I have not tested whether or not you can write the `qspec` to the hash, but if you can't do it in this simple way, it can most certainly be done with a few more changes...)

As for removing the map, I haven't thought about it too hard yet, but we have an API for accessing configurations that use the map. Don't we need this API? I have not used it myself, but maybe this is something that was used in Raft reconfiguration and in the Reconfiguration work of TC (didn't check...) If we don't need the API, then doing as you suggest sounds reasonable.

I think it is beneficial to have config IDs that can be passed between clients and servers and between servers to be able to detect if their configuration has changed, and trigger certain actions based on this ID. I used the ViewID in Jgroup/ARM to implement such things...

**Comment by leandernikolaus** [comment]
I did not find a reference to the config ID API in Gorums Raft. 
If the `qspec` should be part of the config ID, probably we should just add a Hash function to the `qspec` interface.

I think if we have the configuration API (map and retrieval by ID), it is confusing to allow duplicate configurations with the same ID. However, adding a configuration store can easily be done in the application.

**Comment by meling** [comment]
I think we can avoid adding a Hash function to the `QuorumSpec` interface and instead use reflection over the struct... (if we can get to it through the `QuorumSpec` interface).

As for needing a configuration store; I agree applications can handle it easily. But the meta-config solution in TC's master's thesis will need to manage configurations... Not sure if he used these APIs or did his own thing. But either way, it could easily be made part of an internal API rather than exposing it.

PS: There are several existing unresolved issues that also discuss IDs and APIs that we should also consider in relation to this. Issue #30 provide links to the relevant issues. I didn't reread yet.

**Comment by meling** [comment]
Jotting down some notes after telco with Leander about these things.

- We should consider whether or not it makes sense to make `Configuration` and `QuorumSpec` be proto messages, since that would ease marshaling when protocols need to pass around such information. 
- We should consider whether or not we really need the Manager. Leander wants the `Configuration` abstraction to be lightweight, with a single objective to communicate with the nodes in the `Configuration`. It is really the `Node` object that handles connections and so forth, so perhaps we can drop the `Manager` and make things simpler. (This needs more analysis that I didn't do yet).
- To support reconfiguration, we might consider to add another abstraction, e.g. `View`, that contains an `ID` and `Configuration`.
- We also discussed whether or not to keep per call state in the `QuorumSpec` or to create another abstraction for keeping application (or protocol) specific `CallState`.
